[workspace]
members = [
  "cli",
  "server",
  "shared_types",
  "shared",
  "tauri/src-tauri",
  "web-dioxus",
  "web-leptos",
  "web-yew",
]
resolver = "1"

[workspace.package]
authors = ["Red Badger Consulting Limited"]
edition = "2021"
repository = "https://github.com/redbadger/crux/"
license = "Apache-2.0"
keywords = ["crux", "crux_core", "cross-platform-ui", "ffi", "wasm"]
rust-version = "1.66"

[workspace.dependencies]
anyhow = "1.0.75"
serde = "1.0.188"
uuid = { version = "1.4.1", features = ["v4", "wasm-bindgen", "js", "serde"] }
