[package]
name = "crux_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow.workspace = true
clap = { version = "4.3.4", features = ["derive"] }
lsp-server = "0.7.0"
lsp-types = "0.94.0"
serde_json = "1.0.96"
serde.workspace = true
crossbeam-channel = "0.5.8"
