[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
anyhow.workspace = true
async-sse = "5.1.0"
async-std = "1.12.0"
bincode = "1.3.3"
chrono = { version = "0.4.31", features = ["serde"] }
crux_core = "0.6"
crux_http = "0.4"
crux_macros = "0.3"
derive_more = "0.99.17"
futures = "0.3.28"
lazy_static = "1.4.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.49"
uniffi = "0.24.3"
url = "2.4.1"
wasm-bindgen = "0.2.87"

[dev-dependencies]
assert_let_bind = "0.1.1"
insta = { version = "1.33.0", features = ["yaml"] }

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.24.3", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.24.3", features = ["build"] }
