[package]
name = "crux_macros"
description = "Macros for use with crux_core"
authors = ["Red Badger Consulting Limited"]
repository = "https://github.com/redbadger/crux/"
version = "0.3.2"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
keywords = ["crux", "crux_core", "cross-platform-ui", "ffi", "wasm"]
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.3"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.67"
quote = "1.0.33"
syn = "2.0.37"

[dev-dependencies]
insta = "1.33"
prettyplease = "0.2"
