[workspace]
members = ["shared", "shared_types"]
resolver = "1"

[workspace.package]
authors = ["Red Badger Consulting Limited"]
edition = "2021"
keywords = ["tap-to-pay"]
rust-version = "1.68"

[workspace.dependencies]
anyhow = "1.0.75"
serde = "1.0.188"
